version: "3.9"
services:
  rift-analyzer:
    build: .
    environment:
        - DISCORD_TOKEN=${DISCORD_TOKEN}
        - RIOT_API_TOKEN=${RIOT_API_TOKEN}
    volumes:
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logscd