name: Clean code

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
  hadolint:
    runs-on: ubuntu-latest
    name: HadoLint
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile
